-- =============================================================================
-- GEO-AWARE RMS: MASTER PRODUCTION SCHEMA (v5.0)
-- Combines Robust Data Logic with Supabase Auth
-- =============================================================================

-- 1. CLEANUP (Reset Script)


-- 2. ENUMS (Strict Data Types)
CREATE TYPE user_role AS ENUM ('super_admin', 'branch_manager');
CREATE TYPE order_status AS ENUM ('pending', 'accepted', 'in_kitchen', 'out_for_delivery', 'done', 'cancelled');
CREATE TYPE payment_method AS ENUM ('cash', 'credit_card', 'wallet');
CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'failed', 'refunded');

-- 3. BRANCHES
-- Physical locations. 
CREATE TABLE public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone_contact TEXT,
    
    -- Geospatial Data (The Polygon Definitions)
    zones JSONB NOT NULL DEFAULT '[]', 
    
    -- Operational Status
    is_active BOOLEAN DEFAULT TRUE,
    opening_time TIME,
    closing_time TIME,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. PROFILES (Replaces system_users)
-- Links Supabase Auth (UUID) to our System Roles
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE,
    full_name TEXT,
    role user_role DEFAULT 'branch_manager',
    
    -- Security: Link this staff member to a specific branch
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL,
    
    is_active BOOLEAN DEFAULT TRUE,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. CUSTOMERS
-- End-users (Whatsapp Users)
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL UNIQUE,
    full_name TEXT,
    language_pref TEXT DEFAULT 'ar', 
    is_blocked BOOLEAN DEFAULT FALSE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. CUSTOMER ADDRESSES
-- Multiple addresses per customer
CREATE TABLE public.customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    address_text TEXT NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    label TEXT, -- e.g., "Home", "Work"
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. ORDERS (The Robust Transaction Table)
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    daily_seq INTEGER, -- Human readable #1, #2 (Resets Daily)
    
    -- Relationships
    branch_id BIGINT REFERENCES public.branches(id),
    customer_id BIGINT REFERENCES public.customers(id),
    address_id BIGINT REFERENCES public.customer_addresses(id),
    
    -- Order Content
    items JSONB NOT NULL, 
    kitchen_notes TEXT, 

    -- Financials
    subtotal DECIMAL(10,2) DEFAULT 0.00,
    delivery_fee DECIMAL(10,2) DEFAULT 0.00,
    tax DECIMAL(10,2) DEFAULT 0.00,
    discount DECIMAL(10,2) DEFAULT 0.00,
    total_price DECIMAL(10,2) GENERATED ALWAYS AS (subtotal + delivery_fee + tax - discount) STORED,
    
    -- Payment Info
    payment_method payment_method DEFAULT 'cash',
    payment_status payment_status DEFAULT 'pending',

    -- Status Flow
    status order_status DEFAULT 'pending',
    
    -- Delivery Logistics 
    delivery_agent_name TEXT,
    delivery_agent_phone TEXT,

    -- Exception Handling
    cancellation_reason TEXT, 
    cancelled_by UUID REFERENCES public.profiles(id), -- Changed from BIGINT to UUID
    customer_alert_message TEXT, 

    -- Modification Tracking
    modification_pending BOOLEAN DEFAULT FALSE,
    modification_request JSONB, 

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    accepted_at TIMESTAMP WITH TIME ZONE,
    in_kitchen_at TIMESTAMP WITH TIME ZONE,
    out_for_delivery_at TIMESTAMP WITH TIME ZONE,
    done_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE
);

-- 8. INDEXES (Performance)
CREATE INDEX idx_orders_branch_id ON public.orders(branch_id);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_created_at ON public.orders(created_at);
CREATE INDEX idx_customers_phone ON public.customers(phone_number);
CREATE INDEX idx_profiles_user_id ON public.profiles(id);

-- 9. REALTIME ENABLEMENT
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;

-- 10. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Open for Managers)
CREATE POLICY "Public view branches" ON public.branches FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth users view profiles" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth users view orders" ON public.orders FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth users update orders" ON public.orders FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth users insert orders" ON public.orders FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth users manage customers" ON public.customers FOR ALL TO authenticated USING (true);
CREATE POLICY "Auth users manage addresses" ON public.customer_addresses FOR ALL TO authenticated USING (true);

-- 11. AUTOMATION: New Auth User -> Create Profile
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', 'New Manager'),
    'branch_manager'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 12. AUTOMATION: Daily Sequence ID
CREATE OR REPLACE FUNCTION set_daily_id()
RETURNS TRIGGER AS $$
BEGIN
  NEW.daily_seq := (
    SELECT COALESCE(MAX(daily_seq), 0) + 1
    FROM public.orders
    WHERE DATE(created_at) = DATE(NEW.created_at)
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_daily_id
BEFORE INSERT ON public.orders
FOR EACH ROW
EXECUTE FUNCTION set_daily_id();

-- 13. SEED DATA (Optional Branch to Start)
INSERT INTO public.branches (name, phone_contact, zones)
VALUES ('Main Branch', '01012345678', '[]');







-- =============================================
-- 14. ADMIN PERMISSIONS (CRITICAL FIXES)
-- =============================================

-- Allow Admins/Managers to ADD new branches
CREATE POLICY "Enable insert for authenticated users" ON "public"."branches"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (true);

-- Allow Admins/Managers to EDIT branches
CREATE POLICY "Enable update for authenticated users" ON "public"."branches"
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- Allow Admins/Managers to DELETE branches
CREATE POLICY "Enable delete for authenticated users" ON "public"."branches"
AS PERMISSIVE FOR DELETE
TO authenticated
USING (true);







-- Function to get comprehensive customer context by phone number
create or replace function get_customer_context(phone_input text)
returns json
language plpgsql
security definer -- Runs with admin privileges to read data
as $$
declare
    cust_record record;
    addr_list json;
    active_ord json;
    result json;
begin
    -- 1. Get Customer Details
    select * into cust_record from customers where phone_number = phone_input;

    -- If customer does not exist, return a specific structure
    if not found then
        return json_build_object(
            'found', false,
            'message', 'User not found'
        );
    end if;

    -- 2. Get All Addresses for this customer
    select coalesce(json_agg(t), '[]'::json) into addr_list
    from (
        select * from customer_addresses 
        where customer_id = cust_record.id
        order by is_default desc, created_at desc
    ) t;

    -- 3. Get the ONE Current Active Order (Newest first, excluding done/cancelled)
    select row_to_json(t) into active_ord
    from (
        select * from orders
        where customer_id = cust_record.id
        and status not in ('done', 'cancelled')
        order by created_at desc
        limit 1
    ) t;

    -- 4. Build the Final JSON Response
    result := json_build_object(
        'found', true,
        'customer', row_to_json(cust_record),
        'addresses', addr_list,
        'active_order', active_ord 
    );

    return result;
end;
$$;







-- Migration: Add cancellation_dismissed column to orders table
-- Purpose: Track when cancelled order notifications have been dismissed by managers
-- This replaces the localStorage-based approach with a database solution
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS cancellation_dismissed BOOLEAN DEFAULT FALSE;
-- Add index for performance when filtering dismissed cancellations
CREATE INDEX IF NOT EXISTS idx_orders_cancellation_dismissed 
ON public.orders(cancellation_dismissed) 
WHERE status = 'cancelled';
-- Comment for documentation
COMMENT ON COLUMN public.orders.cancellation_dismissed IS 
'Tracks if managers have dismissed the cancellation notification for this order';